language: c

os:
    - linux
    - osx

sudo: false
dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - debhelper
    - libusb-1.0-0-dev
    - pkg-config
    - librtlsdr-dev

before_install:
    - if [ `uname` = "Darwin" ]; then
          brew update;
          brew install -v librtlsdr;
      fi

script:
    - if [ `uname` = "Linux" ]; then
          dpkg-buildpackage -b -us -uc;
      elif [ `uname` = "Darwin" ]; then
          make;
          make test;
      fi
